name: "Deploy BOT"

on:
  issue_comment:
    types: [created]

jobs:
  rebase-and-push:
    name: Rebase and Push to env

    # If the pull request has been merged
    # if: github.event_name == 'issue_comment' && github.event.pull_request.merged == 'true'
    if: contains(github.event.comment.body, '/deploy')
    
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: refs/heads/${{ github.head_ref }} 
    - name: Show GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/github-script@v3
      id: get-pr
      with:
        script: |
          const request = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          }
          core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
          try {
            const result = await github.pulls.get(request)
            return result.data
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`)
          }
    - name: Check User Permission
      uses: actions-cool/check-user-permission@v2.0.1
      with:
        username: ${{ github.actor }}
        require: developer

    - name: Rebase and deploy
      id: rebase
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         SHA_COMMIT: ${{ github.sha }}
        AUTHOR: ${{ github.actor }}
      run: |
        export TARGET_BRANCH=$(printf "${{ github.event.comment.body }}" | cut -d ' ' -f2)
        export SHA_COMMIT="${{ fromJSON(steps.get-pr.outputs.result).head.sha }}"
        chmod +x ./.github/scripts/rebase-and-deploy-to-env.sh
        echo ::set-output name=output::$(./.github/scripts/rebase-and-deploy-to-env.sh)
    - name: Comment on PR
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ steps.rebase.outputs.output }}'
          })
